-
  hosts: cp4mcm_421f3f1f-3349-2955-6a7a-1471021a5d3e
  become: yes
  tasks:
    - name: cpu process
      shell: ps aux --sort -%cpu | head -n5
      register: _process
    - name: プロセス出力
      debug:
        msg: '{{ _process.stdout }}'
    - name: プロセス出力2
      debug: var=_process.stdout_lines
