- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  - name: oc4wkr03 poweron
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      name: oc4wkr03
      state: poweredon
